"""create complete rail saathi schema

Revision ID: c33ed4bd2aa0
Revises: 33d2d15fe4ed
Create Date: 2026-09-13 20:30:16.527645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c33ed4bd2aa0'
down_revision: Union[str, Sequence[str], None] = '33d2d15fe4ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('seat_layout_type', sa.String(length=50), nullable=True),
    sa.Column('default_fare_multiplier', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_number', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('train_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trains_train_number'), 'trains', ['train_number'], unique=True)
    op.create_table('coaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('coach_class_id', sa.Integer(), nullable=False),
    sa.Column('coach_number', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coach_class_id'], ['coach_classes.id'], ),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('train_id', 'coach_number', name='uq_coaches_train_number')
    )
    op.create_index(op.f('ix_coaches_coach_class_id'), 'coaches', ['coach_class_id'], unique=False)
    op.create_index(op.f('ix_coaches_train_id'), 'coaches', ['train_id'], unique=False)
    op.create_table('fare_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_class_id', sa.Integer(), nullable=False),
    sa.Column('rate_per_km', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('minimum_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coach_class_id'], ['coach_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fare_rules_coach_class_id'), 'fare_rules', ['coach_class_id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_train_id'), 'routes', ['train_id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=False),
    sa.Column('operating_days', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_route_id'), 'schedules', ['route_id'], unique=False)
    op.create_index(op.f('ix_schedules_train_id'), 'schedules', ['train_id'], unique=False)
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.String(length=10), nullable=False),
    sa.Column('seat_type', sa.String(length=30), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('column_number', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seats_coach_id'), 'seats', ['coach_id'], unique=False)
    op.create_table('train_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('arrival_offset_minutes', sa.Integer(), nullable=True),
    sa.Column('departure_offset_minutes', sa.Integer(), nullable=True),
    sa.Column('distance_from_origin_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'stop_sequence', name='uq_train_stops_route_sequence')
    )
    op.create_index(op.f('ix_train_stops_route_id'), 'train_stops', ['route_id'], unique=False)
    op.create_index(op.f('ix_train_stops_station_id'), 'train_stops', ['station_id'], unique=False)
    op.create_table('journey_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('journey_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_stop_id', sa.Integer(), nullable=True),
    sa.Column('next_stop_id', sa.Integer(), nullable=True),
    sa.Column('delay_minutes', sa.Integer(), nullable=False),
    sa.Column('actual_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_stop_id'], ['train_stops.id'], ),
    sa.ForeignKeyConstraint(['next_stop_id'], ['train_stops.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'journey_date', name='uq_journey_runs_schedule_date')
    )
    op.create_index(op.f('ix_journey_runs_schedule_id'), 'journey_runs', ['schedule_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('journey_run_id', sa.Integer(), nullable=False),
    sa.Column('source_stop_id', sa.Integer(), nullable=False),
    sa.Column('destination_stop_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('booked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_stop_id'], ['train_stops.id'], ),
    sa.ForeignKeyConstraint(['journey_run_id'], ['journey_runs.id'], ),
    sa.ForeignKeyConstraint(['source_stop_id'], ['train_stops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_reference'), 'bookings', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_bookings_journey_run_id'), 'bookings', ['journey_run_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('booking_passengers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('seat_preference', sa.String(length=30), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=True),
    sa.Column('fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_passengers_booking_id'), 'booking_passengers', ['booking_id'], unique=False)
    op.create_table('booking_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_passenger_id', sa.Integer(), nullable=False),
    sa.Column('journey_run_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('from_stop_id', sa.Integer(), nullable=False),
    sa.Column('to_stop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_passenger_id'], ['booking_passengers.id'], ),
    sa.ForeignKeyConstraint(['from_stop_id'], ['train_stops.id'], ),
    sa.ForeignKeyConstraint(['journey_run_id'], ['journey_runs.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.ForeignKeyConstraint(['to_stop_id'], ['train_stops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_segments_booking_passenger_id'), 'booking_segments', ['booking_passenger_id'], unique=False)
    op.create_index(op.f('ix_booking_segments_journey_run_id'), 'booking_segments', ['journey_run_id'], unique=False)
    op.create_index(op.f('ix_booking_segments_seat_id'), 'booking_segments', ['seat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_segments_seat_id'), table_name='booking_segments')
    op.drop_index(op.f('ix_booking_segments_journey_run_id'), table_name='booking_segments')
    op.drop_index(op.f('ix_booking_segments_booking_passenger_id'), table_name='booking_segments')
    op.drop_table('booking_segments')
    op.drop_index(op.f('ix_booking_passengers_booking_id'), table_name='booking_passengers')
    op.drop_table('booking_passengers')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_journey_run_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_reference'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_journey_runs_schedule_id'), table_name='journey_runs')
    op.drop_table('journey_runs')
    op.drop_index(op.f('ix_train_stops_station_id'), table_name='train_stops')
    op.drop_index(op.f('ix_train_stops_route_id'), table_name='train_stops')
    op.drop_table('train_stops')
    op.drop_index(op.f('ix_seats_coach_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_index(op.f('ix_schedules_train_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_route_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_routes_train_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_fare_rules_coach_class_id'), table_name='fare_rules')
    op.drop_table('fare_rules')
    op.drop_index(op.f('ix_coaches_train_id'), table_name='coaches')
    op.drop_index(op.f('ix_coaches_coach_class_id'), table_name='coaches')
    op.drop_table('coaches')
    op.drop_index(op.f('ix_trains_train_number'), table_name='trains')
    op.drop_table('trains')
    op.drop_table('coach_classes')
    # ### end Alembic commands ###
